Algoritmo "conteate10"


Var
contarmenos, contarmais : inteiro


Inicio
contarmais <- 0
           Enquanto (contarmais<=10) faca
           EscrevaL(contarmais)
           contarmais <- contarmais + 1
           Fimenquanto
           EscrevaL("----TERMINEI A ADIÇAO----")

contarmenos <- 10
         Enquanto (contarmenos>=0) faca
         EscrevaL (contarmenos)
         contarmenos <- contarmenos - 1
         Fimenquanto
         EscrevaL("------Terminei de contar-----")



Fimalgoritmo